### ISSUE TITLE
Release v0.6.2 Checklist

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1494]
# Release Checklist

## Before Release

* [x] Migrate any unresolved Issues or PRs from the [release GitHub project board](https://github.com/scikit-hep/pyhf/projects/16) to a new project board.
* [x] Verify that there is a release notes file for the release under ``docs/release-notes``.
* [x] Verify that the release notes files correctly summarize all development changes since the last release.
* [x] Draft email to ``pyhf-announcements`` mailing list that summarizes the main points of the release notes and circulate it for development team approval.
* [x] Update the checklist file in the ``docs`` directory if there are revisions.
* [x] Verify that the project README is displaying correctly on [TestPyPI](https://test.pypi.org/project/pyhf/).
* [x] Add any new use citations or published probability models to the Use and Citations page.
* [x] Update the [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) GitHub Action used for deployment to TestPyPI and PyPI to the latest stable release.
* [x] Update the ``codemeta.json`` file in the release PR if its requirements have updated.

## Once Release PR is Merged

* [x] Watch the CI to ensure that the deployment to PyPI is successful.
* [x] Create a [GitHub release](https://github.com/scikit-hep/pyhf/releases) from the generated PR tag and copy the release notes published to the GitHub release page. The creation of the GitHub release triggers all other release related activities.
* [x] Verify there is a new [Zenodo DOI](https://doi.org/10.5281/zenodo.1169739) minted for the release.
* [x] Verify that a Binder has properly built for the new release.
* [x] Watch for a GitHub notification that there is an automatic PR to the [Conda-forge feedstock](https://github.com/conda-forge/pyhf-feedstock). This may take multiple hours to happen. If there are any changes needed to the Conda-forge release make them **from a personal account** and not from an organization account to have workflows properly trigger.

## After Release

* [x] Verify that the release is installable from both PyPI and Conda-forge.
* [x] Send the drafted ``pyhf-announcements`` email out from the ``pyhf-announcements`` account email.
* [x] Tweet the release out on both personal and team Twitter accounts.
* [x] Announce the release on the [Scikit-HEP community Gitter](https://gitter.im/Scikit-HEP/community).
* [x] Make a release for the [`pyhf` tutorial](https://github.com/pyhf/pyhf-tutorial) corresponding to the **previous release** number. This release represents the last version of the tutorial that is guaranteed to work with previous release API.
* [ ] Update the tutorial to use the new release number and API.
* [x] Make a PR to use the new release in the [CUDA enabled Docker images](https://github.com/pyhf/cuda-images).
* [ ] Close the release GitHub Project board.

**Comment by kratsg** [comment]
Missing from published probability models:
- https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2018-22
