### ISSUE TITLE
Release v0.6.3 Checklist

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1578]
# Release Checklist

## Before Release

* [x] Migrate any unresolved Issues or PRs from the [release GitHub project board](https://github.com/scikit-hep/pyhf/projects/) to a new project board.
* [x] Verify that there is a release notes file for the release under [``docs/release-notes``](https://github.com/scikit-hep/pyhf/tree/master/docs/release-notes).
   - c.f. PR #1583
* [x] Verify that the release notes files correctly summarize all development changes since the last release.
* [x] Draft email to [``pyhf-announcements`` mailing list](https://groups.google.com/group/pyhf-announcements/subscribe) that summarizes the main points of the release notes and circulate it for development team approval.
* [x] Update the checklist Issue template in the [``.github/ISSUE_TEMPLATE``](https://github.com/scikit-hep/pyhf/tree/master/.github/ISSUE_TEMPLATE) directory if there are revisions.
* [x] Verify that the project README is displaying correctly on [TestPyPI](https://test.pypi.org/project/pyhf/).
* [x] Add any new use citations or published statistical models to the [Use and Citations page](https://scikit-hep.org/pyhf/citations.html).
* [x] Update the [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) GitHub Action used for deployment to TestPyPI and PyPI to the latest stable release.
* [x] Update the ``codemeta.json`` file in the release PR if its requirements have updated.

## Once Release PR is Merged

* [x] Watch the CI to ensure that the deployment to [PyPI](https://pypi.org/project/pyhf/) is successful.
* [x] Create a [GitHub release](https://github.com/scikit-hep/pyhf/releases) from the generated PR tag and copy the release notes published to the GitHub release page. The creation of the GitHub release triggers all other release related activities.
* [x] Verify there is a new [Zenodo DOI](https://doi.org/10.5281/zenodo.1169739) minted for the release.
* [x] Verify that a Binder has properly built for the new release.
* [x] Watch for a GitHub notification that there is an automatic PR to the
  [Conda-forge feedstock](https://github.com/conda-forge/pyhf-feedstock). This may take multiple hours to happen. If there are any changes needed to the Conda-forge release make them **from a personal account** and not from an organization account to have workflows properly trigger.
   - [x]  Verify the requirements in the [Conda-forge feedstock](https://github.com/conda-forge/pyhf-feedstock) recipe `meta.yaml` match those in `setup.cfg` and `pyproject.toml`.

## After Release

* [x] Verify that the release is installable from both [PyPI](https://pypi.org/project/pyhf/) and [Conda-forge](https://github.com/conda-forge/pyhf-feedstock).
* [x] Send the drafted ``pyhf-announcements`` email out from the ``pyhf-announcements`` account email.
* [x] Tweet the release out on both personal and team Twitter accounts.
* [x] Announce the release on the [Scikit-HEP community Gitter](https://gitter.im/Scikit-HEP/community).
* [x] Make a release for the [`pyhf` tutorial](https://github.com/pyhf/pyhf-tutorial/releases) corresponding to the **previous release** number. This release represents the last version of the tutorial that is guaranteed to work with previous release API.
* [x] Update the [tutorial](https://github.com/pyhf/pyhf-tutorial) to use the new release number and API.
* [x] Make a PR to use the new release in the [CUDA enabled Docker images](https://github.com/pyhf/cuda-images).
* [ ] Close the [release GitHub Project board](https://github.com/scikit-hep/pyhf/projects/).

**Comment by matthewfeickert** [comment]
Add to Issue template:

   - [ ]  Verify the requirements in the [Conda-forge feedstock](https://github.com/conda-forge/pyhf-feedstock) recipe `meta.yaml` match those in `setup.cfg` and `pyproject.toml`.

**Comment by matthewfeickert** [comment]
Also need to add checking that both the `latest` tag and the release tag (e.g., `v0.6.3`) are getting deployed to Docker Hub. At the moment only the `latest` tag is and so I've manually tagged and deployed it.

**Comment by matthewfeickert** [comment]
Also copy all the changes that are queued up for you before you paste in the release notes

**Comment by matthewfeickert** [comment]
Note also that the `CITATION.cff` file will cause Zenodo to place the 

https://github.com/scikit-hep/pyhf/blob/248e40072ca933813214ada3fd79b10633ffef1d/CITATION.cff#L34-L42

and the

https://github.com/scikit-hep/pyhf/blob/248e40072ca933813214ada3fd79b10633ffef1d/CITATION.cff#L2

in the "description" entry of the archive.
