### ISSUE TITLE
Roadmap: tensor and optimizer retrievers and backends (e.g. diffability)

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#1648]
- [ ] move the `get_backend` and `set_backend` out of `__init__` (#1646)
- [ ] drop globals for backends (#1646)
- [ ] drop `events` and recomputations (essentially models need to be rebuilt or tied to the backend somehow)
- [ ] drop `default_backend`/`default_optimizer` and consolidate into current backend
